name: GitHub-Profile-3D-Contrib

on:
  schedule: # 02:00 BJT == 18:00 UTC
#     - cron: "0 0 * * *" 此action有误先注释时间
      - cron: ""
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.WSZHU_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 1000
      - name: Commit & Push
        run: |
          git config user.name wushengzhu
          git config user.email ws_zhu@foxmail.com
          git add -A .
          git commit -m "generated"
          git push
